version: '3.3'
services:
  mongodb:
    image: mongo:7.0.2
    restart: always
    container_name: mongodb_grpc_movis
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: grpc-movies
    ports:
      - '27017:27017'
